// <auto-generated />
using GuildManagerServer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildManagerServer.Api.Data.Migrations
{
    [DbContext(typeof(GuildContext))]
    partial class GuildContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GuildManagerServer.Api.Models.CharacterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HairColorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HairId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Instinct")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Presence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("JobId");

                    b.HasIndex("RaceId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("GuildManagerServer.Api.Models.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothe"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leather armor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chain mail"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Plate armor"
                        });
                });

            modelBuilder.Entity("GuildManagerServer.Api.Models.JobModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HealthByLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Instinct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Presence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Job");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dexterity = 0,
                            HealthByLevel = 3,
                            Instinct = 0,
                            Name = "Fighter",
                            Presence = 0,
                            Spirit = 0,
                            Strength = 1
                        },
                        new
                        {
                            Id = 2,
                            Dexterity = 0,
                            HealthByLevel = 2,
                            Instinct = 0,
                            Name = "Bard",
                            Presence = 1,
                            Spirit = 0,
                            Strength = 0
                        },
                        new
                        {
                            Id = 3,
                            Dexterity = 0,
                            HealthByLevel = 1,
                            Instinct = 0,
                            Name = "Mage",
                            Presence = 0,
                            Spirit = 1,
                            Strength = 0
                        });
                });

            modelBuilder.Entity("GuildManagerServer.Api.Models.RaceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Instinct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Presence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Spirit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dexterity = 0,
                            Health = 10,
                            Instinct = 1,
                            Name = "Human",
                            Presence = 1,
                            Spirit = 0,
                            Strength = 0
                        },
                        new
                        {
                            Id = 2,
                            Dexterity = 1,
                            Health = 10,
                            Instinct = 0,
                            Name = "Elf",
                            Presence = 0,
                            Spirit = 1,
                            Strength = 0
                        },
                        new
                        {
                            Id = 3,
                            Dexterity = 0,
                            Health = 10,
                            Instinct = 0,
                            Name = "Tiefling",
                            Presence = 1,
                            Spirit = 1,
                            Strength = 0
                        });
                });

            modelBuilder.Entity("GuildManagerServer.Api.Models.CharacterModel", b =>
                {
                    b.HasOne("GuildManagerServer.Api.Models.EquipmentModel", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildManagerServer.Api.Models.JobModel", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildManagerServer.Api.Models.RaceModel", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Job");

                    b.Navigation("Race");
                });
#pragma warning restore 612, 618
        }
    }
}
