GET http://localhost:5181/api/Character

###
GET http://localhost:5181/api/Character/4

###
POST http://localhost:5181/api/Character
Content-Type: application/json

{
  "Name": "Torak",
  "RaceId": 1,
  "JobId": 1,
  "Level": 1,
  "Strength": 2,
  "Spirit": 0,
  "Presence": -1,
  "Dexterity": 1,
  "Instinct": 0,
  "BodyId": 2,
  "HairId": 1,
  "HairColorId": 2,
  "EquipmentId": 1
}

###
PUT http://localhost:5181/api/Character/5
Content-Type: application/json

{
  "Name": "Eliette",
  "RaceId": 1,
  "JobId": 1,
  "Level": 1,
  "Strength": 0,
  "Spirit": -1,
  "Presence": 2,
  "Dexterity": 0,
  "Instinct": 1,
  "BodyId": 3,
  "HairId": 2,
  "HairColorId": 5,
  "EquipmentId": 1
}

###
DELETE http://localhost:5181/api/Character/4